---
title: "Publications"
output: html_notebook
---

```{r}
library(RSQLite)
fpath = "C:/Users/anush/NEU_resources_and_projects/DBMS/publicationsdb.db"

dbcon <- dbConnect(RSQLite::SQLite(), fpath)
```

```{sql connection=dbcon}
PRAGMA foreign_keys = ON
```


```{sql connection=dbcon}
CREATE TABLE IF NOT EXISTS Course(
  nid TEXT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  lengthInDays NUMBER NOT NULL
)
```

```{sql connection=dbcon}
INSERT INTO Course values 
(1,"DBMS",120),
(2,"Algo",125)
```


```{sql connection=dbcon}
SELECT * FROM Course
```

```{sql connection=dbcon}
DROP TABLE Certifications
```

```{sql connection=dbcon}
CREATE TABLE IF NOT EXISTS Certifications(
  cid NUMBER PRIMARY KEY NOT NULL,
  certification TEXT,
  CHECK (certification IN ('CAP','CSM','CSTE','CBAP','PMP'))
)
```

```{sql connection=dbcon}
CREATE TRIGGER check_certifcations

```

```{sql connection=dbcon}
INSERT INTO Certifications values 
(1,"CAP"),
(2,"CSM")
```


```{sql connection=dbcon}
SELECT * FROM Certifications
```

```{sql connection=dbcon}
CREATE TABLE IF NOT EXISTS Author(
  aid NUMBER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL
)
```

```{sql connection=dbcon}
INSERT INTO Author values 
(1,"Anush"),
(2,"Anirudh"),
(3,"Adithya")
```

```{sql connection=dbcon}
SELECT * FROM Author
```

#CertificationOfAuthor table is the result of normalization. This makes it easy.

```{sql connection=dbcon}
CREATE TABLE IF NOT EXISTS CertificationsOfAuthor(
  cid NUMBER NOT NULL,
  aid NUMBER NOT NULL,
  PRIMARY KEY(cid,aid),
  FOREIGN KEY (aid) REFERENCES Author(aid),
  FOREIGN KEY (cid) REFERENCES Certifications(cid)
)
```

```{sql connection=dbcon}
SELECT * FROM CertificationsOfAuthor
```

```{sql connection=dbcon}
CREATE TABLE IF NOT EXISTS Topic(
  tid NUMBER PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  lengthInHrs NUMBER NOT NULL,
  subject TEXT NOT NULL,
  aid NUMBER NOT NULL,
  UNIQUE(subject),
  FOREIGN KEY (aid) REFERENCES AUTHOR(aid) ON DELETE SET NULL
)
```

```{sql connection=dbcon}
SELECT * FROM Topic
```


```{sql connection=dbcon}
CREATE TABLE IF NOT EXISTS CourseTopic(
  nid NUMBER NOT NULL,
  tid NUMBER NOT NULL,
  PRIMARY KEY(nid,tid),
  FOREIGN KEY (tid) REFERENCES Topic(tid),
  FOREIGN KEY (nid) REFERENCES Course(nid)
)
```

```{sql connection=dbcon}
SELECT * FROM CourseTopic
```

#seperate table for email-ids to avoid multivalued attributes.

```{sql connection=dbcon}
drop table EmailIds
```

```{sql connection=dbcon}
CREATE TABLE IF NOT EXISTS EmailIds(
  aid NUMBER NOT NULL,
  email TEXT PRIMARY KEY NOT NULL,
  FOREIGN KEY (aid) REFERENCES Author(aid)
)
```

#Correct values for email IDs
```{sql connection=dbcon}
INSERT INTO EmailIds (aid, email) VALUES (1,"anush@gmail.com"),(2,"anirudh@yahoo.com")

```

#Displaying the EmailIds Table
```{sql connection=dbcon}
SELECT * FROM EmailIds
```

```{r}
dbDisconnect(dbcon)
```
